const noticeData = [
    {
        index: 1,
        category: '공지사항',
        title: '제 14회 게임콘서트 개최 안내',
        img: '01-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 2,
        category: '공지사항',
        title: '넷마블게임박물관 건립준비캠페인',
        img: '01-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 3,
        category: '공지사항',
        title: '[게임소통학교] 도미노 영상 이벤트 결과 발표',
        img: '01-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 4,
        category: '공지사항',
        title: '제 14회 게임콘서트 개최 안내',
        img: '01-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 5,
        category: '공지사항',
        title: '넷마블게임박물관 건립준비캠페인',
        img: '01-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 6,
        category: '공지사항',
        title: '[게임소통학교] 도미노 영상 이벤트 결과 발표',
        img: '01-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
];

const newsData = [
    {
        index: 1,
        category: '뉴스룸',
        title: '넷마블장애인선수단, ‘2022 추계전국장애인조정대회’에서 총 17개 메달 획득',
        img: '02-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 2,
        category: '뉴스룸',
        title: '게임아카데미 부트캠프 2기 온라인 수료식 개최',
        img: '02-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 3,
        category: '뉴스룸',
        title: '넷마블게임박물관 건립준비캠페인',
        img: '02-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 4,
        category: '뉴스룸',
        title: '넷마블장애인선수단, ‘2022 추계전국장애인조정대회’에서 총 17개 메달 획득',
        img: '02-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 5,
        category: '뉴스룸',
        title: '게임아카데미 부트캠프 2기 온라인 수료식 개최',
        img: '02-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 6,
        category: '뉴스룸',
        title: '넷마블게임박물관 건립준비캠페인',
        img: '02-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
];

const snsData = [
    {
        index: 1,
        category: '소셜미디어',
        title: '<제 12회 게임콘서트> 바로보기',
        img: '03-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 2,
        category: '소셜미디어',
        title: '<제 11회 게임콘서트 2부> Q&A',
        img: '03-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 3,
        category: '소셜미디어',
        title: '<제 11회 게임콘서트> 바로보기',
        img: '03-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 4,
        category: '소셜미디어',
        title: '<제 12회 게임콘서트> 바로보기',
        img: '03-01.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 23',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 5,
        category: '소셜미디어',
        title: '<제 11회 게임콘서트 2부> Q&A',
        img: '03-02.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 09. 14',
        url: 'https://www.netmarblefoundation.org/',
    },
    {
        index: 6,
        category: '소셜미디어',
        title: '<제 11회 게임콘서트> 바로보기',
        img: '03-03.jpg',
        content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, debitis ipsa ratione aspernatur sit corporis consequatur nam nesciunt aliquam tenetur rerum eius distinctio ex mollitia?',
        date: '2022. 08. 18',
        url: 'https://www.netmarblefoundation.org/',
    },
];

export {noticeData, newsData, snsData};